name: ci
on: [push, pull_request]
jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "pypy-3.8"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: |
          pip install -r requirements
          pip install --upgrade coveralls
      - name: Test with pytest
        run: CI=1 DANGER=1 POG_PASSPHRASE="hunter2" coverage run -m unittest
      - name: merge coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coverage combine --append /tmp
          coveralls --service=github
